// This file is generated by FlutterFire CLI
// You will replace this file with your own after running flutterfire configure

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARRzAOAwBN5UsGoZ4Ne7EtHQJfTG6-nWY',
    appId: '1:642177916129:web:7ca5bc8da4d542bdd2eba0',
    messagingSenderId: '642177916129',
    projectId: 'edulearn-57970',
    authDomain: 'edulearn-57970.firebaseapp.com',
    storageBucket: 'edulearn-57970.firebasestorage.app',
    measurementId: 'G-SBHJ57EEJT',
  );

  // PLACEHOLDER - Replace with your actual Firebase configuration

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLclU0Amr-gHPMhq7wQYbQfqDHTLbq58k',
    appId: '1:642177916129:android:db32c84c6123832cd2eba0',
    messagingSenderId: '642177916129',
    projectId: 'edulearn-57970',
    storageBucket: 'edulearn-57970.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyR8ceXMyXEiBaTAbAbyrCXQbvayv431Y',
    appId: '1:642177916129:ios:e165a5def487d555d2eba0',
    messagingSenderId: '642177916129',
    projectId: 'edulearn-57970',
    storageBucket: 'edulearn-57970.firebasestorage.app',
    iosBundleId: 'com.example.eEducation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyR8ceXMyXEiBaTAbAbyrCXQbvayv431Y',
    appId: '1:642177916129:ios:e165a5def487d555d2eba0',
    messagingSenderId: '642177916129',
    projectId: 'edulearn-57970',
    storageBucket: 'edulearn-57970.firebasestorage.app',
    iosBundleId: 'com.example.eEducation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARRzAOAwBN5UsGoZ4Ne7EtHQJfTG6-nWY',
    appId: '1:642177916129:web:8914665887c56020d2eba0',
    messagingSenderId: '642177916129',
    projectId: 'edulearn-57970',
    authDomain: 'edulearn-57970.firebaseapp.com',
    storageBucket: 'edulearn-57970.firebasestorage.app',
    measurementId: 'G-TSRJVF0ETK',
  );

}